In [3]:
import pandas as pd

In [4]:
df1=pd.read_csv("/content/employee_productivity_dataset.csv")

In [5]:
df1.head(5)

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5,50000.0,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0,45000.0,Mumbai
2,E003,John Mathew,Finance,NaN,Male,Onsite,10-03-2022,45.0,6,NaN,60000.0,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,NaN,5,4.2,52000.0,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8,NaN,Pune

In [ ]:
df1.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Gender', 'Work_Mode',
       'Join_Date', 'Hours_Worked_Per_Week', 'Projects_Completed',
       'Performance_Score', 'Salary', 'Location'],
      dtype='object')

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            250 non-null    object
 1   Name                   250 non-null    object
 2   Department             250 non-null    object
 3   Age                    225 non-null    float64
 4   Gender                 250 non-null    object
 5   Work_Mode              250 non-null    object
 6   Join_Date              250 non-null    object
 7   Hours_Worked_Per_Week  200 non-null    float64
 8   Projects_Completed     250 non-null    int64
 9   Performance_Score      200 non-null    float64
 10  Salary                 225 non-null    float64
 11  Location               250 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 23.6+ KB

Q1. Handle Missing Values (Basic Cleaning)
Fill missing values using the following:
Age → Median
Salary → Mean
Hours_Worked_Per_Week → Median
Performance_Score → Mean
Display the dataset after handling missing values

In [ ]:
df1['Age'].fillna(df1['Age'].median(),inplace=True)

/tmp/ipykernel_1649/1265047744.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna(df1['Age'].median(),inplace=True)

In [ ]:
'''Salary → Mean
Hours_Worked_Per_Week → Median
Performance_Score → Mean
Display the dataset after handling missing values'''
df1['Salary'].fillna(df1['Salary'].mean(),inplace=True)
df1['Hours_Worked_Per_Week'].fillna(df1['Hours_Worked_Per_Week'].median(),inplace=True)
df1['Performance_Score'].fillna(df1['Performance_Score'].mean(),inplace=True)

/tmp/ipykernel_1649/3148664432.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Salary'].fillna(df1['Salary'].mean(),inplace=True)
/tmp/ipykernel_1649/3148664432.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Hours_Worked_Per_Week'].fillna(df1['Hours_Worked_Per_Week'].median(),inplace=True)
/tmp/ipykernel_1649/3148664432.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Performance_Score'].fillna(df1['Performance_Score'].mean(),inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Employee_ID            250 non-null    object
 1   Name                   250 non-null    object
 2   Department             250 non-null    object
 3   Age                    250 non-null    float64
 4   Gender                 250 non-null    object
 5   Work_Mode              250 non-null    object
 6   Join_Date              250 non-null    object
 7   Hours_Worked_Per_Week  250 non-null    float64
 8   Projects_Completed     250 non-null    int64
 9   Performance_Score      250 non-null    float64
 10  Salary                 250 non-null    float64
 11  Location               250 non-null    object
dtypes: float64(4), int64(1), object(7)
memory usage: 23.6+ KB

In [ ]:
df1.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,40.0,5,4.5000,50000.000000,Pune
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,38.0,4,4.0000,45000.000000,Mumbai
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,45.0,6,4.3125,60000.000000,Bangalore
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,41.0,5,4.2000,52000.000000,Delhi
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,50.0,7,4.8000,50666.666667,Pune

Q2. Label Encoding
Convert these columns into numeric values using Label Encoding:
Gender
Department
Show the updated columns

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lab_encodr=LabelEncoder()
df1['gender_encoded']=lab_encodr.fit_transform(df1['Gender'])
df1['department_encoded']=lab_encodr.fit_transform(df1['Department'])

In [ ]:
df1[['gender_encoded','department_encoded']]

     gender_encoded  department_encoded
0                 1                   2
1                 0                   1
2                 1                   0
3                 0                   2
4                 1                   3
..              ...                 ...
245               0                   1
246               1                   0
247               0                   3
248               1                   2
249               0                   1

[250 rows x 2 columns]

Q3. One-Hot Encoding
Apply One-Hot Encoding on:
Work_Mode

Location

Display the dataset and check how many new columns are created **bold text**

In [ ]:
df1_encoded=pd.get_dummies(df1,columns=['Work_Mode','Location'],dtype=int)

In [ ]:
df1_encoded.head(5)

,Employee_ID,Name,Department,Age,Gender,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,gender_encoded,department_encoded,Work_Mode_Hybrid,Work_Mode_Onsite,Work_Mode_Remote,Location_Bangalore,Location_Delhi,Location_Mumbai,Location_Pune
0,E001,Amit Sharma,IT,25.0,Male,15-01-2021,40.0,5,4.5000,50000.000000,1,2,0,0,1,0,0,0,1
1,E002,Riya Patel,HR,30.0,Female,15-02-2020,38.0,4,4.0000,45000.000000,0,1,1,0,0,0,0,1,0
2,E003,John Mathew,Finance,29.0,Male,10-03-2022,45.0,6,4.3125,60000.000000,1,0,0,1,0,1,0,0,0
3,E004,Sneha Joshi,IT,28.0,Female,22-04-2021,41.0,5,4.2000,52000.000000,0,2,0,0,1,0,1,0,0
4,E005,Arjun Verma,Marketing,35.0,Male,18-05-2020,50.0,7,4.8000,50666.666667,1,3,1,0,0,0,0,0,1

In [ ]:
#earlier dataset before encoding
print("dataset before encoding is:---->",df1.shape)
print("dataset after encoding is:---->",df1_encoded.shape)

dataset before encoding is:----> (250, 14)
dataset after encoding is:----> (250, 19)

that means after one hot encoding 5 new columns are added in the dataframe.

Q4. Normalization (Min-Max Scaling)
Normalize the following columns:
Salary
Hours_Worked_Per_Week
Use MinMaxScaler and display results

**Q4**. Normalization (Min-Max Scaling)
Normalize the following columns:
Salary
Hours_Worked_Per_Week
Use MinMaxScaler and display results

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scal_minmax=MinMaxScaler()
df1[['Salary','Hours_Worked_Per_Week']]=scal_minmax.fit_transform(df1[['Salary','Hours_Worked_Per_Week']])

In [ ]:
df1.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Gender', 'Work_Mode',
       'Join_Date', 'Hours_Worked_Per_Week', 'Projects_Completed',
       'Performance_Score', 'Salary', 'Location', 'gender_encoded',
       'department_encoded'],
      dtype='object')

In [ ]:
df1[['Salary','Hours_Worked_Per_Week']]

       Salary  Hours_Worked_Per_Week
0    0.347826               0.285714
1    0.130435               0.142857
2    0.782609               0.642857
3    0.434783               0.357143
4    0.376812               1.000000
..        ...                    ...
245  0.000000               0.000000
246  1.000000               0.857143
247  0.260870               0.428571
248  0.391304               0.357143
249  0.043478               0.071429

[250 rows x 2 columns]

In [ ]:
df1.head()

,Employee_ID,Name,Department,Age,Gender,Work_Mode,Join_Date,Hours_Worked_Per_Week,Projects_Completed,Performance_Score,Salary,Location,gender_encoded,department_encoded
0,E001,Amit Sharma,IT,25.0,Male,Remote,15-01-2021,0.285714,5,4.5000,0.347826,Pune,1,2
1,E002,Riya Patel,HR,30.0,Female,Hybrid,15-02-2020,0.142857,4,4.0000,0.130435,Mumbai,0,1
2,E003,John Mathew,Finance,29.0,Male,Onsite,10-03-2022,0.642857,6,4.3125,0.782609,Bangalore,1,0
3,E004,Sneha Joshi,IT,28.0,Female,Remote,22-04-2021,0.357143,5,4.2000,0.434783,Delhi,0,2
4,E005,Arjun Verma,Marketing,35.0,Male,Hybrid,18-05-2020,1.000000,7,4.8000,0.376812,Pune,1,3


**Q5.** Standardization (Scaling)
Apply StandardScaler on:
Age
Projects_Completed
Display the transformed values

In [8]:
from sklearn.preprocessing import StandardScaler

In [ ]:
std_scal=StandardScaler()
df1[['Age','Projects_Completed']]=std_scal.fit_transform(df1[['Age','Projects_Completed']])

In [ ]:
df1[['Age','Projects_Completed']]

          Age  Projects_Completed
0   -1.172018           -0.211604
1    0.000000           -0.916949
2   -0.234404            0.493742
3   -0.468807           -0.211604
4    1.172018            1.199088
..        ...                 ...
245 -0.703211           -1.622295
246  2.344036            1.904433
247 -0.234404            0.493742
248  0.234404           -0.211604
249 -0.937614           -0.916949

[250 rows x 2 columns]

**Q6.** Compare Scaling Methods
Apply both:

MinMaxScaler

StandardScaler

On the Salary column.

Show both results side by side

In [ ]:
# creating new column of salary data to perform both scaling method

salary_data = df1[['Salary']].dropna()

In [ ]:
type(salary_data)
salary_data.head()

     Salary
0  0.347826
1  0.130435
2  0.782609
3  0.434783
4  0.376812

In [ ]:
# Applying both methods of scaling on the newly created salary column of df1 dataframe
minmax_salary = MinMaxScaler().fit_transform(salary_data)
std_salary = StandardScaler().fit_transform(salary_data)

In [ ]:
type(minmax_salary)

numpy.ndarray

In [ ]:
print(minmax_salary.flatten())

[0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826 0.34782609 0.13043478
 0.7826087  0.43478261 0.37681159 0.         1.         0.26086957
 0.39130435 0.04347826 0.34782609 0.13043478 0.7826087  0.43478261
 0.37681159 0.         1.         0.26086957 0.39130435 0.04347826
 0.34782609 0.13043478 0.7826087  0.43478261 0.37681159 0.
 1.         0.26086957 0.39130435 0.04347826]

In [ ]:
comparison_df = pd.DataFrame({
    'MinMax_Scaled_Salary': minmax_salary.flatten(),
    'Standard_Scaled_Salary': std_salary.flatten()
})

In [ ]:
comparison_df.head()

   MinMax_Scaled_Salary  Standard_Scaled_Salary
0              0.347826           -9.745089e-02
1              0.130435           -8.283326e-01
2              0.782609            1.364312e+00
3              0.434783            1.949018e-01
4              0.376812           -3.732632e-16

In [2]:
'''
Q7. Build Preprocessing Pipeline
Create a pipeline that:
Applies encoding to categorical columns
Applies scaling to numerical columns
Use:
ColumnTransformer
Pipeline'''

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

In [6]:
df1.columns

Index(['Employee_ID', 'Name', 'Department', 'Age', 'Gender', 'Work_Mode',
       'Join_Date', 'Hours_Worked_Per_Week', 'Projects_Completed',
       'Performance_Score', 'Salary', 'Location'],
      dtype='object')

In [7]:
num_cols = ['Age', 'Salary', 'Hours_Worked_Per_Week', 'Projects_Completed', 'Performance_Score']
cat_cols = ['Gender', 'Department', 'Work_Mode', 'Location']

**Q9**. Conceptual Question
Why is scaling important in Python

**answer:-**featire scaling in machine learming is critical because algorithms are highle sensitive to the magnoitude of data.larger magnitude can disproportionate the model thus leading to poor performancs and biased results
scaling transform the numerical magnitude into a comparable range so that the machine learning model treats them comfortably

**q10**:-Why do we convert categorical data into numerical form?

**answer10**:- Why do we convert categorical data into numerical form because machine learning algorithms understand only the numerical data not the text data as the algorithm perform different mathematical calculation which can be done only on numerical data not in text data. thus to perform the model activity fluently er convert the categorical data to numerical.

**assignment_ends**