In [1]:
import pandas as pd

**SECTION 1**

Q1. What is a Decision Tree? Explain its structure (Root, Nodes, Leaves) with a real-life example.
**ANSWER** 1:- a  decision tree is a superviseed machin learning used for classificatin and regression both, It breaks down a dataset into smaller subsets for building a associated tree like flowchart.

tree structure  has following items:-

1. root node:- this is the topmost or say the dead of the tree. it represent the entire dataset and chooses the best initial feature to split.
2. internal nodes:-Sub-nodes that split into further sub-nodes. They represent a specific test condition or evaluation point on an attribute.
3. Decision (Internal) Nodes:- they are the sub-noded that further splits in to subnodes.
 They represent a specific test condition or evaluation point on an attribute.

3:- leaves(terminal nodes):- hey are the final nodes that doesnot split further.they represented the final predicted values.

real-ife example:a) whether to go office by car/ metro or twowheeler.
root node: are you late?
Yes Leaf Node: choose the faster one
.If no: can choose any one.
 Decision Node:is it the peak traffic hour?

 If Yes  Leaf Node:choose metro .
 If No Leaf Node: pick the comfortable vehicle.

**question 2**:-Differentiate between Gini Impurity and Entropy. Which one is used by default in Scikit-learn and why?

**anser2**:- gini impurity is the metric used to 	Measures the probability of a random sample based on the distribution. while
entropy Measures the total amount of randomness, disorder, or impurity in a subset.

gini impurity  value range between 0.0 (pure) and 0.5 (equally distributed).and entrpy values range Between \0.0 (pure) and 1.0 (equally distributed).
giniimpurity computation is faster as it requies only simple arithmetic squares while entropy requires logarithmic calculations.

in Scikit-learn-gini impurity is used by default.

**question3**:- What is Overfitting in Decision Trees.How can we detect it using training and testing accuracy?
**answer3**:- Overfitting occurs when a decision tree grows too deep, learning specific noise, outliers, and random fluctuations in the training dataset rather than generalized patterns.
we can detect overfitting by comparing the accuracy scores of your training data against your testing data

Q4. Explain Pruning in Decision Trees.What is the difference between Pre-pruning and Post-pruning?

answer4:- Pruning is the process of removing sub-sections of a decision tree that add little predictive value. It simplifies the model structure to prevent overfitting.

**Q5**. What is Feature Importance?How can it help businesses in decision-making?
**answer5**:- feature importance is the metric that measures how valuable each input variable was during the formation of decision tree.  its helps the business in decision making in the following ways:-
a)   market strategies  making: as  it detemines which features actually drives the result/desired uotput.
b)helps in resource optimation by ignoring useless or less important featores thus saving time, money and energy.
c) explainability.

###############             ** section2 ################**

In [2]:
#Q6 a)   Load the dataset
df=pd.read_csv("/content/bank.csv")

In [4]:
# b) Display first 5 rows
df.head(5)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes

In [5]:
# Q6. c) Shape
df.shape

(11162, 17)

In [6]:
#d) Data types
df.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
deposit      object
dtype: object

In [7]:
# e) Column names
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

interpretion
the dataset has both numerical and categorical columns

In [8]:
#Q7. Data Cleaning
#Check for missing values
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [11]:
# Check for duplicates
print(df.duplicated().sum())

0

intertetion:- the dataset has no null values present  also there is no duplicate values present.

In [14]:
# Q8. Data Preprocessing
# Convert categorical variables into numerical.

from sklearn.preprocessing import LabelEncoder

In [20]:
lab=LabelEncoder()
cat_cols=df.select_dtypes(include=['object']).columns
for col in cat_cols:
  df[col]=lab.fit_transform(df[col])
df[col]

0        1
1        1
2        1
3        1
4        1
        ..
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64

In [21]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,0,1,1,0,2343,1,0,2,5,8,1042,1,-1,0,3,1
1,56,0,1,1,0,45,0,0,2,5,8,1467,1,-1,0,3,1
2,41,9,1,1,0,1270,1,0,2,5,8,1389,1,-1,0,3,1
3,55,7,1,1,0,2476,1,0,2,5,8,579,1,-1,0,3,1
4,54,0,1,2,0,184,0,0,2,5,8,673,2,-1,0,3,1

interpretetion: here label encoder  method is for encoding categorical data encoding. label encoder will convert the catrgorical data in 0,1,2.....

Why is encoding necessary for Decision Trees?

decision tree creation involves vatoious mathmatical  computation which can only be done on the numerical data and for categorical data it is not possible.

In [23]:
# Q9. Feature Selection & Splitting
from sklearn.model_selection import train_test_split
#in this dataset the target variable y
# is categorical (binary text "yes" or "no")
X=df.drop('deposit',axis=1)
y=df['deposit']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8929, 16)
(2233, 16)
(8929,)
(2233,)

importance of splitting:-Splitting data creates an unbiased test benchmark.As  It isolates a portion of data the model never observes during training validating  whether the model has learned  the patterns correctly

In [26]:
# Q10. Model Building
# Train a Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=42)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5, random_state=42)

the max depth control is the maximun height to which the tree can grow down from its root node.

In [28]:
'''
Q11. Model Evaluation
Perform:
Accuracy score
Confusion Matrix
Classification Report'''

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Model Predictions

y_pred = model.predict(X_test)

#metrics

accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

In [29]:
print("Accuracy Score:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)

Accuracy Score: 0.8051948051948052
Confusion Matrix:
 [[867 299]
 [136 931]]
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.74      0.80      1166
           1       0.76      0.87      0.81      1067

    accuracy                           0.81      2233
   macro avg       0.81      0.81      0.81      2233
weighted avg       0.81      0.81      0.80      2233

interpretetion:- the model achieves a high overall baseline accuracy of approx ~89-90%.
prevision measures the percentage of predicted "yes" that are correct.and  Recall measures how many true positive buyers the model successfully detected.

In [30]:
'''Q12. Overfitting Check
Calculate:
Training accuracy
Testing accuracy'''
train_accuracy = model.score(X_train, y_train)
test_accuracy = model.score(X_test, y_test)

In [31]:
print("Training Accuracy:", train_accuracy)
print("Testing Accuracy:", test_accuracy)

Training Accuracy: 0.8149848807257252
Testing Accuracy: 0.8051948051948052

 your training accuracy and testing accuracy values should be close to one another.•  The model is well-fitted and is not overfitting.

In [32]:
# Q13. Pruning Experiment
pruned_model = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=42)
pruned_model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=42)

In [33]:
print("Training Accuracy:", pruned_model.score(X_train, y_train))
print("Testing Accuracy:", pruned_model.score(X_test, y_test))

Training Accuracy: 0.7778026654720573
Testing Accuracy: 0.7653381101656964

In [34]:
'''Q14. Feature Importance
Extract top 5 important features'''
feature_importances = model.feature_importances_
feature_names = X.columns
importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})
importance_df = importance_df.sort_values(by='Importance', ascending=False)
top_features = importance_df.head(5)
print(top_features)

     Feature  Importance
11  duration    0.595239
8    contact    0.121729
13     pdays    0.084299
6    housing    0.067469
10     month    0.054023

clearly, the duration feature(the length of the last phone call conversation) displated as a most inflential feature followed by features like poutcome (previous marketing campaign outcome) and month.

Q15. Business Insights
Based on your model:
Answer15:
Which type of customers are more likely to say “yes”?
What strategy should a bank us

answer15:-  cusyomers who have a long call durations i.e  who are  engsged for long duration, and those customers previously responded positively to prior outreach campaigns.

   ** **********assignment ends****************