In [2]:
# answer1

import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("/content/assignment.csv")

In [7]:
df

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West
...,...,...,...,...,...,...,...
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [8]:
# to didplsy top 5 rows
df.head(5)

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [10]:
# to disply and inderstand tha dataset we can use either info or describe function
df.describe()

        Quantity        Price
count  98.000000    95.000000
mean    5.959184   820.526316
std     2.871540   611.170030
min     1.000000    92.000000
25%     3.250000   426.000000
50%     6.500000   669.000000
75%     8.000000   985.000000
max    10.000000  2901.000000

In [37]:
# anser2:

missing_values = df.isnull().sum().sum()
print("total missing values in the dataset are",missing_values)

total missing values in the dataset are 12

In [31]:

df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [72]:
#answer3:-

quantity_mean = df['Quantity'].mean()
print(quantity_mean)
df['Quantity'].fillna(df['Quantity'].mean(),inplace=True)
df.isnull().sum()

df['Price'].fillna(df['Price'].mean(),inplace=True)
df.isnull().sum()

5.959183673469388

/tmp/ipykernel_1299/2362211000.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mean(),inplace=True)
/tmp/ipykernel_1299/2362211000.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(),inplace=True)

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            0
Price               0
Date                0
Region              2
Revenue             7
dtype: int64

In [62]:
#answer4:-

df.dropna(subset=['Product Category', 'Region'])

df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
Revenue             7
dtype: int64

In [75]:
#answer5:-

df['Revenue']=np.multiply(df['Quantity'].values,df['Price'].values)
df.head(5)

In [76]:
#answer6:-

total_revenue = np.sum(df['Revenue'].values)
print("total revenue generated i thr datast is",total_revenue)

total revenue is 491834.8711063373

In [79]:
#answer7:-
category_revenue = df.groupby('Product Category')['Revenue'].sum()
print("--- Total Revenue by Product Category --->>",category_revenue)

--- Total Revenue by Product Category --->> Product Category
Beauty          28691.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            60512.090226
Name: Revenue, dtype: float64

In [87]:
#answer8:-

# to find the top3 product category firter sort in ascending orderso that the top product categories comes at the top
sorted_categories = category_revenue.sort_values(ascending=False)

# now to find top3 categories
print("Top 3 Product Categories are ---->>>>")
sorted_categories.head(3)

print("now the last  3 Product Categories are ---->>>>")
sorted_categories.tail(3)

Top 3 Product Categories are ---->>>>
now the last  3 Product Categories are ---->>>>

Product Category
Books        29597.938776
Beauty       28691.000000
Groceries    11978.000000
Name: Revenue, dtype: float64

In [90]:
#nswer9: -
region_revenue = df.groupby('Region')['Revenue'].sum()

#to find the region with the highest revenue
region_revenue.idxmax()
print(region_revenue.idxmax())

#to find the region with the lowest revenue
region_revenue.idxmin()
print(region_revenue.idxmin())

North
West

In [ ]:
#answer10:-

df['Date']= pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month

onthly_revenue = df.groupby('Month')['Revenue'].sum()

print(monthly_revenue)